### ISSUE TITLE
Add 'i18n' to description

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#136]
On Zulip someone was having trouble finding the module when they typed in `i18n` in the Project Installer -- I think adding this in the description of the module in the info file would solve that.

**Comment by laryn** [comment]
Or it's a core issue where we should make sure this happens by default...

**Comment by indigoxela** [comment]
> having trouble finding the module when they typed in i18n in the Project Installer...

Yeah, the project installer search is quite... quirky.

Although i18n is part of the title, the module can't be found with the default installer search. Instead one finds modules, that just mention "i18n" somewhere in their readmes - related or not. :stuck_out_tongue_winking_eye: 
Same here: https://backdropcms.org/modules?s=i18n

The quickest solution might actually be, to mention the module machine name additionally somewhere in the README.
:grimacing:

**Comment by indigoxela** [comment]
This [commit](https://github.com/backdrop-contrib/i18n/commit/cd6073f831b6817fb6eb9a638c6ce204e882a620) should improve things.
As the readme gets fetched automatically from B-org, this might already be sufficient. We'll see tomorrow or so (caching on B-org).
If that doesn't work, I'll dig a bit deeper. I didn't check, yet, how this search index (or views search?) is built there.

**Comment by indigoxela** [comment]
Oh, it already works. :wink:
