### ISSUE TITLE
Throws error right after installation

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/i18n#16]
I tested in a multsite environment, putting the module into /sites/demo1/modules/i18n-1.x
 
Right after activating the module, I got the error Error: 

Class 'i18n_field' not found in i18n_get_object() (line 455 of /home/lugoture/www/SERVER/sites/demo1/modules/i18n-1.x/i18n.module).

**Comment by mazzech** [comment]
![Screenshot 2020-03-16 at 13 01 27](https://user-images.githubusercontent.com/5985692/76757077-3d9a7500-6787-11ea-8d91-191fa70b3955.png)

**Comment by indigoxela** [comment]
Did you apply any patch of the current PR?

**Comment by indigoxela** [comment]
This one fixes i18n_field: https://github.com/backdrop-contrib/i18n/pull/12

**Comment by indigoxela** [comment]
And THAT is the actual issue for **i18n_field**: https://github.com/backdrop-contrib/i18n/issues/11

So this one's a duplicate. :wink:
