### ISSUE TITLE
Taxonomy Translation Test

### ISSUE THREAD

**Issue by mazzech** [backdrop-contrib/i18n#21]
Hi @indigoxela thank you for doing the initial port... here's my first feedback
- Created a new vocabulary
- Chose the option "Localize"
- Create a term in three languages (EN = base language)
- Create a taxonomy reference field
- Create an article in EN, choosing the EN term
- Translate into FR, but the taxonomy field does not show the DE term as an option, which should be the case IMO

![Screenshot 2020-04-07 at 10 23 45](https://user-images.githubusercontent.com/5985692/78646936-1d5b6300-78ba-11ea-995d-310ffbd4c056.png)
![Screenshot 2020-04-07 at 10 21 27](https://user-images.githubusercontent.com/5985692/78646938-1df3f980-78ba-11ea-9056-da0b48c0d9d5.png)
![Screenshot 2020-04-07 at 10 19 09](https://user-images.githubusercontent.com/5985692/78646944-1f252680-78ba-11ea-85b5-52d1d6e689a8.png)
![Screenshot 2020-04-07 at 10 12 57](https://user-images.githubusercontent.com/5985692/78646946-1fbdbd00-78ba-11ea-81ba-a1fbea1d5195.png)

**Comment by indigoxela** [comment]
@mazzech many thanks for taking the time to test.

One thing confuses me: your first screenshot shows a totally outdated UI. It should actually look like this screenshot (only one tab "Multilingual support", where the multilingual settings only appear when Multilingual support is checked):
![multilingual-tab](https://user-images.githubusercontent.com/842066/78648950-0b2ef400-78bd-11ea-8af0-a349acacc113.png)

Maybe your testing instance needs an updated version of i18n?

https://github.com/indigoxela/i18n/archive/i18n-taxonomy.zip

Get the latest zip file (from my fork), unzip and rename to i18n, then flush caches and give testing another try.

**Comment by mazzech** [comment]
OK, your link is different from mine... I am not used to Github, where do I usually find the right links for testing modules? 

https://github.com/backdrop-contrib/i18n/archive/1.x.zip (i used this one, upper right corner of this page)
https://github.com/indigoxela/i18n/archive/i18n-taxonomy.zip (seems to be from YOUR repo?)

**Comment by indigoxela** [comment]
Ah, a misunderstanding... :wink: 

The latest changes aren't merged yet. As i18n is a pretty complex module and the changes it needs are rather big, I asked for additional testing in advance.

**Comment by mazzech** [comment]
No problem...;-) But where do I *usually* find the right link (also for future testing and for other modules where someone asks for help testing?)

**Comment by indigoxela** [comment]
@mazzech the link you chose first would usually be the right one to test the current dev (if you want to avoid the usage of git).

**Comment by indigoxela** [comment]
@mazzech The PR has been merged now. If you're still interested in testing it, you now should download the latest dev version from here https://github.com/backdrop-contrib/i18n/archive/1.x.zip.

(Or git clone, of course, for people who prefer git.)

**Comment by mazzech** [comment]
Hi @indigoxela 

thank you... I still do not the translated term in the respective language (e.g. when editing the node in French)

![Screenshot 2020-04-10 at 19 59 37](https://user-images.githubusercontent.com/5985692/79012250-2e300100-7b66-11ea-8060-01f588b96630.png)
![Screenshot 2020-04-10 at 19 58 57](https://user-images.githubusercontent.com/5985692/79012252-2f612e00-7b66-11ea-98c8-bf3f8081fa97.png)

**Comment by indigoxela** [comment]
> I still do not the translated term in the respective language

Question: what settings does the Vocabulary (TaxOne4All ?) have? Translate or localize or fixed?

**Comment by mazzech** [comment]
Oops... "localized"
![Screenshot 2020-04-11 at 10 26 51](https://user-images.githubusercontent.com/5985692/79039081-121c7600-7bdf-11ea-889a-1c8d224cab05.png)
 of course:-)

**Comment by mazzech** [comment]
However, it works when looking at the frontend, taxonomy term is translated

![Screenshot 2020-04-10 at 20 06 32](https://user-images.githubusercontent.com/5985692/79039098-2fe9db00-7bdf-11ea-8e6c-f7f4a60d5291.png)
![Screenshot 2020-04-10 at 20 06 27](https://user-images.githubusercontent.com/5985692/79039099-30827180-7bdf-11ea-9b24-a5b164489eef.png)
![Screenshot 2020-04-10 at 20 06 22](https://user-images.githubusercontent.com/5985692/79039100-30827180-7bdf-11ea-9571-94626c43558c.png)

**Comment by indigoxela** [comment]
Tipp 1: compare that to a Drupal 7, if you find the time.

Tipp 2: selection should be properly filtered for vocabs with setting "translate".

**Comment by mazzech** [comment]
To be honest, all my D7 i18n projects used Entity Translation.

**Comment by mazzech** [comment]
Let's put it that way: what is the intended use case I should test or recreate?

- User A creates Article B in German, chooses category "Dienstleistungen"
- User B translates to English, category "Services" already defined
- Or something similar?

**Comment by indigoxela** [comment]
> all my D7 i18n projects used Entity Translation

Ah, OK, nontheless your testing is helpful here.

Regarding the autocomplete showing other languages - that's a bug in D7 also. Currently we're not trying yet to make i18n for Backdrop better than the D7 version. (We will though later on...).

> what is the intended use case I should test or recreate?

I hoped, that you have some use-case in mind already. But you already wrote that you're not actually using i18n in D7. Hm... Then simply play around and see if you manage to get any php notice/warning/error.

**Comment by mazzech** [comment]
My use case IS that the do editors see the taxonomy terms in their language (node edit form). 
On the frontend, things seems to work pretty well:-)

**Comment by indigoxela** [comment]
> My use case IS that the do editors see the taxonomy terms in their language (node edit form).

Yeah - which is a bug in D7 also. See my previous comment.

**Comment by mazzech** [comment]
Wait... I did use i18n a lot in D7, but with field translation (Entity Translation). But to be honest, I always had the "localize" requirement (one vocabulary for all languages, but with translated term name)

**Comment by mazzech** [comment]
OK, so using checkboxes instead of autocomplete would should work?

**Comment by mazzech** [comment]
Hmmmh, not really...
![Screenshot 2020-04-11 at 11 10 58](https://user-images.githubusercontent.com/5985692/79039952-2f544300-7be5-11ea-8a37-5e6a917f8349.png)

Oh, depends on language negotiation settings:-)
![Screenshot 2020-04-11 at 11 12 14](https://user-images.githubusercontent.com/5985692/79039980-5e6ab480-7be5-11ea-97a5-6a3ecba5ffdf.png)

**Comment by mazzech** [comment]
Seems that I have to test with different users with different language settings.

**Comment by indigoxela** [comment]
@mazze: If in doubt, have a look at the D7 issues (only a subset...):

- https://www.drupal.org/project/i18n/issues/2689251
- https://www.drupal.org/project/i18n/issues/2506981

Please do not expect from me that I already fixed all the D7 issues. It took 50 commits to get the modules running on Backdrop without crashes and exceptions and errors :wink:

**Comment by mazzech** [comment]
@indigoxela no, I do not expect that at all, and believe me, I really appreciate your work, also because I know the complexity of i18n pretty well (including on other systems).

Let me do more test with different users (which is a more realistic scenario anyway;). I will come back to you soon:-)

**Comment by indigoxela** [comment]
> ...one vocabulary for all languages, but with translated term name

And you always used "localize" for that? Translate might have been the better option.

> Let me do more test with different users ... more realistic scenario ...

Sure, you're welcome. And always inspect the dblog for php problems.

**Comment by mazzech** [comment]
"Translate" means different vocabulary structure per language, IMO. I really never had that requiremen. It always worked perfectly with "same structure, localized term names"

**Comment by indigoxela** [comment]
@mazzech I'm trying to clean up the i18n issue queue a bit. There hasn't been activity in this issue since April last year, so I think this one could get closed.

Feel free to reopen, if you still have questions or hints.
