### ISSUE TITLE
Get i18n Simpletests working

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/i18n#22]
All the modules have Simpletests, which currently don't work yet.

I'll see if I can get them back to life. Having working tests is crucial for a possible stable release.

**Comment by indigoxela** [comment]
`1655 passes, 0 fails, 0 exceptions, and 544 debug messages.`

All submodules that are supposed to work have their tests passing now.

**Comment by serundeputy** [comment]
we should get these to run in travisCI too; we can either re-open this or start a new issue ... what do you think?
