### ISSUE TITLE
Drop obsolete db table columns / tables and modules

### ISSUE THREAD

**Issue by indigoxela** [backdrop-contrib/i18n#34]
The "language" columns need evaluation. Core provides new "langcode" columns that took over the job (taxonomy terms...).

As soon as  #33 is done, drop the obsolete ones if that didn't happen yet. And, of course, also remove obsolete db table schemas from install files.

And remove the unportable/unported modules.

**Comment by herbdool** [comment]
@indigoxela I've added a PR to update tables for i18n_menu, i18n_string, i18n_taxonomy. Changes to i18n_path.install are just basic cleanup.

**Comment by indigoxela** [comment]
> I've added a PR to update tables for i18n_menu, i18n_string, i18n_taxonomy. Changes to i18n_path.install are just basic cleanup.

All Travis checks have failed. So I probably need to inspect things locally. Currently I do have the impression that this PR is doing step 2 before step 1. There are some changes that cause head scratching...

**Comment by indigoxela** [comment]
@herbdool although your PR isn't usable as-is (it has several issues), it was a valuable help to get some progress with my upgrade path branch. See https://github.com/backdrop-contrib/i18n/compare/d7-upgrade-path

Your PR tries to do a lot more than the issue description suggests - I'll stick with the initial idea:

1. i18n_taxonomy finalize language to langcode switch in update hook and cleanup
2. i18n_menu finalize language to langcode switch in update hook and cleanup
3. make unportable/obsolete submodules empty placeholders (for migration path)

This should all be done in the branch, now.

**Comment by herbdool** [comment]
I tested all my PRs a few times on a real d7 upgrade that I'm in the middle of. I don't think this one did much. The one thing I added for convenience was adding back the textgroup column in the update hook since it otherwise doesn't work as is.

**Comment by indigoxela** [comment]
The obsolete modules have been handled. The remaining task here is to verify, that all obsolete tables / table columns get dropped, when their data got migrated.

**Comment by herbdool** [comment]
I've checked the tables on my D7 upgrade and can confirm the tables and columns get dropped. It looks good to me.

**Comment by indigoxela** [comment]
I found one leftover table: i18n_block_language.

Resolved in 76361bfd

**Comment by herbdool** [comment]
Now that there's a language option for blocks do you think it would be possible to convert them? Won't be easy since the blocks are in the JSON config.

**Comment by indigoxela** [comment]
> Now that there's a language option for blocks do you think it would be possible to convert them?

This already happens in i18n_update_1003() - blocks with translations keep their translations. Or what do you mean with "convert them"?

In case that update hook doesn't work for you, please open a new issue. This issue here handles leftover tables. :wink:

**Comment by indigoxela** [comment]
Table variable_store is still around, but that might contain a lot of other data, which other modules might want to take care of.
So better not drop it.

**Comment by herbdool** [comment]
Ah, I haven't looked at this in a while so I forgot

**Comment by indigoxela** [comment]
> Ah, I haven't looked at this in a while

Maybe your local i18n isn't up to date anymore? There have been several commits recently.

**Comment by herbdool** [comment]
I wasn't looking at the code, just off the top of my head. One client has this module from a recent download of the main branch. But since there's no release yet I don't know what we're missing.

**Comment by indigoxela** [comment]
> But since there's no release yet I don't know what we're missing.

Getting out a release soon is the main goal. I think, we might be ready for an alpha, but a little more testing would give me more confidence.
