### ISSUE TITLE
Testing i18n - Multilingual content

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/i18n#40]
Continue testing sub-modules of i18n.

Start with activating Multilingual content.

Message: You must enable the Content Translation module to install Multilingual content.
Would you like to continue with the above?

Click CONTINUE.

OK, no errors.

Go to: admin/structure/types/manage/page

Super! The same as known from Drupal 7!

![Screenshot-201](https://user-images.githubusercontent.com/14857883/100553173-ea287280-3294-11eb-84f5-49c8eef8ab8c.png)

There seems exists some error - I marked it with red on screenshot.

These options are especially useful and are not in the core multilingual settings:

• Set current language as default for new content.
• Require language (Do not allow Language Neutral).

For many users, this is a protection against unpleasant errors, if they forget to choose a language, the system saves page / node as Language Neutral and this leads to many problems, including transliteration problems and then search engine optimization problems. 

It is great that the i18n solves this in Backdrop as well.

* * *

The good news ends here. 

After making the changes presented in the above screenshot, I went to the home page, it is available, and has tabs View, Edit and new - Translate. Nice!

But when I try to access Edit / Translate of the front page, like any other old page on the site, created before Multilingual content activation, the site is covered by an error message:

![Screenshot-202](https://user-images.githubusercontent.com/14857883/100553263-95392c00-3295-11eb-8ced-c7ce3fc4fdc9.png)

In newly created pages everything works normally, those that were created before activating Multilingual content and the entered settings as in screenshot above are not available and show the above message.

Disable and uninstall Multilingual content.

Open and edit and save Page / Multilingual support again. I tried everything I could think of - I removed the Multilingual support option altogether, I deleted all URL aliases, I deleted the cached information many times, nothing helps - for all old pages, before installing Multilingual content I see the error:

![Screenshot-202](https://user-images.githubusercontent.com/14857883/100553303-05e04880-3296-11eb-94a0-c3ac683ac649.png)

At the same time, new pages created after the installation of Multilingual content work normally and perfectly.

Even worse, things didn't improve even after i18n was completely disabled and uninstalled.

I also deactivate and uninstall the Core module Content Translation.

Hooray, the pages are available again!

I activate the again Core module Content Translation

The pages are not available again and the same error is visible - The page isn’t redirecting properly.

I go to Page - Multilingual support - and turn on Enabled.

The pages are not available again and the same error is visible.

I go to Languages ​​and delete the Bulgarian language again.

The old pages begin start accessible again, although they disappear from the main menu, they are accessible through a content review, but in the Language field it of these pages it displays "None".

I am installing Bulgarian again.

The pages become inaccessible again, the same error is displayed - The page isn’t redirecting properly.

This time all the pages, even the test one page that worked newly created after the initial installation of Multilingual content - even this page no longer works.

**Conclusions**:

The Multilingual content module is not yet ready for use. Creates errors, problems that cannot be fixed even by completely disabling and uninstalling i18n. 

This is a useful direction of work with great potential, but it is not yet ready for end consumers.

I like the direction i18n is going - so far I see an opportunity to use Field translation - this submodule works well. The associated String translation also seems to be working.

In the coming days and if possible I will test other submodules from i18n.

But I wonder if all the submodules in the i18n bundle need to be ready for the i18n to be officially introduced. Can't it be formalized gradually as the working modules are made official, while the rest are finalized.

**Comment by indigoxela** [comment]
@amilenkov many thanks for testing!

> There seems exists some error - I marked it with red on screenshot.

Nested fieldsets are currently broken (in core). Here's the [core issue](https://github.com/backdrop/backdrop-issues/issues/4766). So that part isn't an i18n issue.

Regarding redirects I have to dig a bit. Not sure yet, what's actually causing the redirection loop, core or i18n, or the combination.

**Comment by indigoxela** [comment]
I'm not able to reproduce the redirection loop yet. At least, not by only uninstalling "Multilingual content". Which step might be missing?

A question: do the inaccessible pages have existing url redirects?

Another question: do you have "Translation redirect" enabled?

**Comment by amilenkov** [comment]
@indigoxela 

Do you want to send you URL address, username and password for full administrator account for the i18n test site?

I am currently copying the current state and configuration to another test domain in different hosting account because I plan to start building the real (not test site) site which I worked on yesterday from all over again and install i18n on a brand new default Backdrop system because I suspect that the problems come from the things I did on this site before installing i18n.

This way you will be able to analyze the problems on another domain, with a copy of the problematic installation from yesterday, which domain is mine and there is no way to harm any client.

There are only three plain text pages on this real client's website, I'm just starting work on it, I will save them as text files on my computer and re-enter them if I can install i18n (I just need content translation to work).

Because this site will be developed in Bulgarian and English and I would really like to do it with i18n even in an unofficial version. 

I'm sure the i18n will continue to evolve finally to official version, but I know from previous experience that even in Drupal 7 it's a good idea to install the i18n before any other multilingual work.

**Comment by indigoxela** [comment]
> Do you want to send you URL address, username and password for full administrator account

@amilenkov sure, maybe I'm able to figure out, how I can reproduce the problem. Email: testi18n(a)indigofloat.at, username - indigoxela, pw - I should be able to reset it anyway.

> I know from previous experience that even in Drupal 7 it's a good idea to install the i18n before any other multilingual work

I know, i18n has never been the easiest module to use, but it shouldn't break things.

**Comment by amilenkov** [comment]
@indigoxela

I will create test account later tonight or tomorrow. An hour ago I changed the DNS servers of my test domain and now I'm waiting for it to become available to do the Backdrop installation and transfer the content and configuration from the problem site.

I also want to make sure that the problems occurs after moving the site to the new domain.

After doing this, I will create a new administrator account which will automatically send the standard newly created account message to the specified your email.

And later I will use the same test domain to test the other i18n sub-modules - before using them on a real site.

I also see that your site is in German, so I think it's good to add German in addition to Bulgarian after installing i18n for better testing.

**Comment by indigoxela** [comment]
> I will create test account later tonight or tomorrow.

No need to rush.

English or German is fine, Bulgarian alone would be too hard for me. :wink:

**Comment by amilenkov** [comment]
I meant to add German for testing i18n because English is out of the system and does not require multilingual support.

**Comment by amilenkov** [comment]
@indigoxela

A new user with username indigoxela has been created on the i18n test site with e-mail testi18n(a)indigofloat.at and a login and password setting message should be received at this email address.

If there are problems you can request a password change at 

https://i18n.site/user/login

**Comment by indigoxela** [comment]
Solved. The problem was caused by the "Global redirect" module. Disabling it fixed the redirection loop for existing nodes.

**Comment by amilenkov** [comment]
@indigoxela

Thank you so much! And I see that it's not really the problem in Global redirect, but in one of its settings - Language Path Checking.

After the pages became available for editing, I saw that they have an undefined language, I set the language to be Bulgarian, I re-activated Global redirect, including Language Path Checking and currently the test site is working normally.

But I have not yet activated Multilingual content in i18n - I do not have more time today, I will continue testing with the test site further. Thank you again!

**Comment by amilenkov** [comment]
@indigoxela

One preliminary question before I checked everything in i18n - in the current state of i18n is there a way to translate the home page - the one that is configured via Site information? Or can this be done in another way? I'm doing it with Redirect for now, but this redirects to a translation of the home page with a separate URL, not to the home page with the specified language Path prefix or subdomain.

**Comment by indigoxela** [comment]
> One preliminary question before I checked everything in i18n - in the current state of i18n is there a way to translate the home page

With "translate" you probably mean "set the frontpage to something different per language"?

No, that's not in i18n anymore (would require the variables module which won't get ported to Backdrop). You can achieve pretty much the same with either:

- A view that shows collections of nodes in current language
- Layouts with visibility settings
- A simple node with translations

Oh, and there's an existing issue in the core issue queue regarding that, but I didn't find it.

**Comment by amilenkov** [comment]
@indigoxela

Thanks a lot for the guidance!

I activated Multilingual content in i18n and using your tips I made a multilingual homepage on the test site. I did it first with Views - Promoted content but I didn't like the Views-specific formatting of the home page.  If content is displayed, then the title becomes a H2 link, if the fields are displayed, I couldn't show the language links at the bottom of the page. But it was a useful experience. I used the user language as a filter and the Promoted Content setting only for the pages intended for the home page.

Then I did it with Layouts with visibility settings with the homepage template and Existing content block. That's it goes perfectly. 

I can now start writing a guide for making multilingual sites :-)

With Views it becomes too complicated, including having more code on the page, with Layouts it becomes more elegant and simple.

I worked with Multilingual content for hours, I made all sorts of changes and settings, the system behaves perfectly, no errors or problems.

I believe that the Multilingual content submodule is ready to work and I will use it in real sites. As well as Field Translate.

One only has to change the accumulated stereotypes from working with Drupal and learn to work fully with Layouts - this is a great tool, including for creating a multilingual site.

In the coming days I will continue to test and share my impressions of working with other submodules.

The results are visible in the test site - https://i18n.site - I made it trilingual - Bulgarian, German and English.

Your account on the site is active. If another developer wants me to create an account for him to test what is going there, just post a username and e-mail here.

**Comment by amilenkov** [comment]
One note just to add, I think it's better in Layouts not to have the homepage template with path "home" - this prevents having a real English page with path "home". There may be another way, but I changed path = "front" for this template and this allowed the English page to have a "home" url.

**Comment by indigoxela** [comment]
> I can now start writing a guide for making multilingual sites :-)

Yes, sure, do so. :wink: 

> I believe that the Multilingual content submodule is ready to work and I will use it in real sites. As well as Field Translate.

That's good news, many thanks again for testing!

> In the coming days I will continue to test and share my impressions of working with other submodules.

Looking forward to get your feedback.

**Comment by amilenkov** [comment]
@indigoxela

In accordance with your instructions, I tried an option to make a multilingual home page with Homepage Layout with Existing content blocks - three blocks that show a Page node, respectively translated into the three languages ​​with Visability condition for each of the three blocks - Site language.

Here I find a problem that I don't know if it's due to the i18n or the Backdrop system. If I'm wrong, please advice where to fix it, if it's from the system or i18n, I think it needs to be fixed.

Initially I set the Page title block to be No title, and in the Existing content block I choose to use Use Content Title as a title and this title is formatted by Style Settings to be H1 and with class page-title - in such way the title in the home page follows the same CSS styles as the other pages on the site. And I mage a sub-theme with some custom CSS for Bartik to make design of home page equal to others. The change occurred for the home page due to the lack of a standard Page title.

In appearance, everything looks good, but I find another problem - in the HTML code.

The HTML code of the home page differs in HTML code from the other pages. There is an empty `<div class = "l-page-title">` on the home page, which is probably the place for the standard Page title, which does not exist because (Page = No title), but the DIV tag exists as redundant empty code, and this seems to be wrong - simply useless empty code.

In addition, such a difference in the code (In this way Tile is inside the Existing content block) seems to me a potential complication of the design in future development of site design - will require different CSS rules for the title and design of the home and other pages, which may be saved if the title is the standard Page title .

So I decided to remove No title from the Page title block and set the Page title block to display the title from the Existing content block in order to avoid this empty redundant code described above in <div class = "l-page-title">. At the same time in the Existing content block I configure the title not to be displayed (no title)

At this point, another and more unpleasant problem appears! The title from the Existing content block is not recognized, the same Home title is displayed for all languages ​​- I don't know if this comes from the English translation of the home page, which has such a title or somewhere from the system, but in other languages ​​it also shows no their translated title, and the title of all translations on the home page is "Home".

When you have the opportunity you can check on the test site, I left the system in this state.

And one more question, I apologize for the worries I create, but I guess it affects a lot of users:

When I use Existing content block the content of the existing page is displayed, but not the tabs Review, Edit, translation under the title. Is there a way to restore this - it would be useful for users who do not have access or do not know how to edit the home page and its translations through the list of all content.

You can see on the site that I also made a Custom block for the home page and it has been translated into all three languages. At the moment it is not active but I tested this feature as well - in this way multilingual home page works well and even this way is simpler structurally, but it still seems to me that through the Existing content block it is preferable because when the home page is a node, it can be taxonomized, performed in other places , to use with Views, it can be customized with fields, etc.

**Comment by amilenkov** [comment]
@indigoxela

In Backup and Migrate / Saved backups on the https://i18n.site test site, I started saving full copies of the Entire site, which can be downloaded and the site be copied to another testing system or locally testing.

Configuration is also saved as Source: Configuration in Saved backups.

In addition to backing up the site recovery data, this also allows you to save previous site states, for this purpose I also add descriptions to each backup.

**Comment by indigoxela** [comment]
@amilenkov Thanks again for testing, but I'm not sure, what you're currently testing and if it has anything to do with the i18n modules. :wink: 

BTW: Here's the [core issue](https://github.com/backdrop/backdrop-issues/issues/3500) for start page per language.

**Comment by amilenkov** [comment]
@indigoxela 

Yes, this is not directly related to i18n in Backdrop given the lack of a Backdrop version for Variabes. In Drupal 7, a multilingual homepage is made as I think exactly with i18n using Variables. And since multilingual front page is, among other things, multilingual content, and because  I didn't know where else to post for my attempts to make a multilingual homepage, I put this post on this page for testing the Multilingual content submodule.

Thanks for the link to the core issue for start page per language. From now on, I will publish my observations, questions and suggestions on a multilingual homepage there.

I apologize for my inexperience. I don't know where or how I can check what open issues are being discussed about Backdrop on GitHub - so I can post in the right place.

Thank you very much for your help.

On https://github.com/backdrop-contrib/i18n there is written:

Port is ongoing and we need help. If you're willing to test functionality and/or provide pull requests, feel free to open an issue. Your help is highly appreciated!

I simply try to do that, to test and help testing, I'm sorry if I do it wrong sometimes.

**Comment by indigoxela** [comment]
> I apologize for my inexperience.

@amilenkov No need to excuse at all, your contribution is really appreciated!

**Comment by indigoxela** [comment]
@amilenkov Again, many thanks for your testing and feedback.

You had some trouble with setting the frontpage per language - i18n can't provide that anymore, but in the meantime, there's a new module for that (totally unrelated to i18n): https://backdropcms.org/project/frontpage_multilingual

Maybe that one works for you. It should be easier to use compared to the i18n_variable module. (Much, much easier...)

**Comment by amilenkov** [comment]
@indigoxela

Thank you for the information!

I found out about frontpage_multilingual module almost as soon as it was published on the module page - I check it regularly, at least once a week, often and several times a week, I like to read what's new there. I don't know if there is an option to subscribe somewhere for information about new modules, if there is I would subscribe.

The fact that there is already a frontpage_multilingual already exists is wonderful, but I haven't used it on a real site yet.

I am currently developing a multilingual site (Bulgarian & English)  with a small online store (16 products only) and have been researching Ubercart intensively in recent days. I have done test installations for Ubercart for both Backdrop and Drupal 7. Ubercart has problems with string translation (for me) and tomorrow I will install i18n to see if this will help. I think this will be a useful check. Then I will write more on the questions asked today. Thanks!
