### ISSUE TITLE
Testing i18n - Menu translation

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/i18n#41]
Activate Menu translation.

Message: You must enable the Translation sets module to install Menu translation.
OK, I also activate the Translation sets module.

Checking admin/config/regional - Regional and language

A new section has appeared - Translation sets - currently empty - No translation sets available.

I see another new section - config/regional/date-views - I don't know what it's for, but I'll probably find out later. For now, I ignore it.

I go to admin/structure/menu

And here I see the Translation sets tab - it is currently empty - No translation sets available.- I assume the same one, which is also available through admin/config/regional. I guess here data will appear in the process of working on the menus

I go to admin /structure/menu/manage/main-menu

There is a new option here - Translate Menu. It is strange that for Primary navigation source is Bulgarian. Guess why this is so and make changes to admin/config/regional/i18n/strings and set Source language - English.

I return to admin/structure/menu/manage/main-menu/translate

OK, now everything is normal, for Primary navigation I already have English (source)

I translate Primary navigation  into Bulgarian and German.

Works properly, I think this is an additional useful option (which is not in the core) for a multilingual site with users / administrators using different languages.

I go to admin/structure/menu/manage/main-menu/configure.

OK, there's a whole new section here: Multilingual options. I know that from Drupal.

1. No multilingual options for menu items. Only the menu will be translatable. It is clear.
2. Translate and Localize. Menu items with language will allow translations. Menu items without language will be localized.
3. Fixed Language. Menu items will have a global language and they will only show up for pages in that language.

For point 3, I wonder if I need it because the Backdrop system does it with Core. I decide to see what the difference is and activate.

I see the difference. In a system without i18 n, menu items can be placed in different languages. However, i18n adds a new Translate tab to the Edit link page.

I translate all the pages, I also translate the menus. I already understand what Translation sets are - they have already appeared:

admin/structure/menu/manage/translation.

Conclusions:

For e Menu translation sub-module works reliably, I  worked continuously for 5-6 hours on this test and made hundreds of settings, tests and changes, the system did not give a single error.

A useful option is to translate the name of the menu itself.

However, I don't understand what Translation sets and the translation of the links in the menu do in general, because in Core you can still set the language for the link and this works perfectly in core and the menu shows only the links that are with the language that is active on the site. So I wonder if this is necessary in Backdrop?

A new option is to create menus with a fixed language, this can be a useful option in some cases. Also No multilingual options for menu items. Only the menu will be translatable - may be useful in some cases

I believe that the module Menu translation is ready for use and can be officially published.

However, I assume that the benefit of Translation sets and menu links translation (which largely do something that the Backdrop core already does, unlike Drupal 7 where you need i18n for such functionality) will become clearer to me by activating the Path translation module in next tests or when adding Views links in different languages in menus. As far as I remember from old experience In Drupal 7, they work together (menus and paths), so I've done translations of pages made with Views that display content in different languages without translating from one View to another.

I would also be grateful for information on what config/regional/date-views is for.

**Comment by indigoxela** [comment]
> However, I don't understand what Translation sets and the translation of the links in the menu do in general, because in Core you can still set the language for the link and this works perfectly

Core allows to *set* a language, but i18n allows to *relate* them to their translations. The difference is subtle but it exists.
There's some work going on to improve the menu item handling in core. It might happen, that parts of i18n_menu get obsolete.
We'll see.

In my opinion the i18n_menu submodule is not the most needed anymore, but some people might find it useful. It provides different menu item strategies - which makes it hard to understand, unfortunately (translate vs. localize...).

> I would also be grateful for information on what config/regional/date-views is for.

It has absolutely nothing to do with i18n. :wink: It ships with the core Date module and allows to define custom date formats for views calendar pagers.

**Comment by indigoxela** [comment]
The first alpha version has been released. A lot of changes happened in the meantime, so I'm closing this issue. Feel free to open new ones, if you discover any problems. Please read the [release notes](https://github.com/backdrop-contrib/i18n/releases/tag/1.x-1.0.0-alpha) for that alpha before updating.
