### ISSUE TITLE
Testing i18n - Taxonomy translation

### ISSUE THREAD

**Issue by amilenkov** [backdrop-contrib/i18n#42]
I also tested Taxonomy translation at the same system and with same configuration described in the previous tests.

In the settings of the core dictionary Tags I activated Multilingual support with the option "Translate".

On admin/structure/types/manage/page/fields I added Term reference field Tags.

On a node on the site from Content type Page I added a few Tags in Bulgarian and then translated them into English and German.

Everything works perfectly, clearly, understandably and without any error messages.

I will not do more tests, I think that i18n is ready to work and I start using it in real sites. If there are problems in working with real sites, I will post new issues.

**Comment by indigoxela** [comment]
@amilenkov many thanks for all your testing!
