### ISSUE TITLE
i18n_variable: backdrop_multilingual() does not exist

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/i18n#49]
I get a fatal error on updating from d7 where it gets an undefined function `backdrop_multilingual()` which gets called in hook_init so pretty much all the time. When starting the upgrade i18n_variable is still enabled so we need to ensure this doesn't break things.

**Comment by indigoxela** [comment]
It seems that the hidden i18n_variable module causes several problems when upgrading.

The function should be: `language_multilingual()` (was drupal_multilingual() before).

Fix is (hopefully) on the way. See https://github.com/backdrop-contrib/i18n/commit/c466383d5c2063fda1ce5be579be7ef460394b3c

**Comment by indigoxela** [comment]
Fixed. In the meantime all code from deprecated modules got removed.
