### ISSUE TITLE
Views and i18n [meta]

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#52]
- [ ] https://github.com/backdrop-contrib/i18n/issues/64 View that lists localized terms
 - [ ] https://github.com/backdrop-contrib/i18n/issues/63 Views exposed filters

---------

Pulling out a few comments from an [earlier thread](https://github.com/backdrop-contrib/i18n/issues/1#issuecomment-612033255):

> @laryn: Should **[i18n Views](https://www.drupal.org/project/i18nviews)** be wrapped (back) in since Views is in core now?

> @mazzech: I used i18n Views several times, there are a few hickups, but the workarounds without the module are pretty dirty... ++ for having it migrated:-)

> @indigoxela: Regarding i18n Views: I never needed it because views labels and header/footer text areas are translatable as-is, without any additional modules. At least in D7 - didn't need it yet in Backdrop. But if it works in D7, it should work in B core (or we should fix it there).

**Comment by herbdool** [comment]
Are you suggesting putting that module into this one? Or port it with dependency on i18n?

**Comment by laryn** [comment]
@herbdool My question is whether it should be merged into this module -- mostly because Views is in core now. If I read it right, it used to be part of `i18n` and was at one point removed:

> This module has been moved from Internationalization package so we can have different branches compatible with each of the Views versions.

**Comment by indigoxela** [comment]
The first thing I'd check: isn't i18n_views obsolete?

Views strings are translatable again since B 1.16.3. Before we put any effort in this, we should verify that it's really necessary.

**Comment by laryn** [comment]
I've come across a situation where pieces of `i18nviews` are needed. I think perhaps we can just pull out the relevant handlers and add them directly to the appropriate submodule in `i18n` rather than requiring a separate `i18nviews` module.

The port that is working for me on this dev site in question is here:
https://github.com/laryn/i18nviews

Maybe we can just pluck pieces out of there as we need them. @indigoxela says "Most of the other stuff just duplicates everything that core and i18n already provide."

**Comment by herbdool** [comment]
Some of i18nviews may need to go into core too since basic localization and views are already in core. We'll need to figure out what goes where.

**Comment by indigoxela** [comment]
TBH, I'm a bit unhappy with this meta. In Drupal [i18nviews](https://www.drupal.org/project/i18nviews) is an extra module.

The i18n suite is a monster on its own, and not so easy to maintain. Incorporating other modules, which includes migration paths, is a little much for the small maintainer team (cough) of i18n.

**Comment by laryn** [comment]
I get it, and you're the boss.

**Comment by laryn** [comment]
One case where I've found I need to use the `i18nviews` functionality is on exposed filters for taxonomy terms. For example, you want filters that people can select but you want to use the localized version of the term names.

@indigoxela should I close this issue and open a core issue to see if this is something that might be possible for core inclusion (and if not just finish the `i18nviews` port and release that? Or do you think that functionality belongs in `i18n`?

**Comment by herbdool** [comment]
I think the best is to do the `i18nviews` port. Translating views gets complicated quickly.

**Comment by indigoxela** [comment]
I'm not really familiar with i18nviews. Plucking out pieces might make it even harder for maintainers and users.

Taxonomy terms are already tricky, because some functionality re term translation went into core and now things overlap a bit. But rewriting i18n is above my head (and available time).

So, for now it's probably best to fully port i18nviews.

**Comment by laryn** [comment]
Will do. Thanks.
