### ISSUE TITLE
Argument 1 passed to backdrop_sort() must be of the type array, null given

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#6]
`Recoverable fatal error: Argument 1 passed to backdrop_sort() must be of the type array, null given, called in /home/public_html/core/includes/token.inc on line 320 and defined in backdrop_sort() (line 6904 of /home/public_html/core/includes/common.inc).`

Above error came when editing a field (happened on both a text field and an image field) while I had `Internationalization (i18n)`, `String translation`, and `Translation sets` modules active. Disabled the last two (but left i18n enabled) and was able to edit the field.

**Comment by indigoxela** [comment]
I wasn't able to reproduce this. OK, the issue is pretty old and very likely outdated. :wink: 

If you still see that fatal error, please reopen this issue (and provide the steps to reproduce).
