### ISSUE TITLE
i18n_string localized term translation doesn't use CKEditor for description

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#66]
I noticed when translating localized terms that the description displays HTML code instead of using the CK Editor as expected. PR coming.

**Comment by indigoxela** [comment]
@laryn many thanks for your PR, I'll look into this ASAP, but maybe not before weekend.

**Comment by laryn** [comment]
Hmm... it's actually not working completely. I hadn't actually tried saving the translation, which produces an SQL syntax error with this PR.

**Comment by indigoxela** [comment]
@laryn should be fixed in 16c2a2e1. Please test thoroughly, the automated tests are passing, but "human eyes" still might find something. :smiley:

**Comment by laryn** [comment]
Manually patched my dev site and did some testing -- basic functionality is looking good! A few visual/UI suggestions that come to mind as I am testing:

- can the submit button be wrapped in a `'#type' => 'actions'` array? I think this gives the button more consistent styling with the rest of the UI
- Adding the CKEditor interface also adds "Formatting options" so the manually added description is duplication:
![Screenshot_2021-04-19 Translate to Español](https://user-images.githubusercontent.com/871421/115271941-7bdd3300-a103-11eb-846c-035f38c313d1.png)
 - The CKEditor editing window opens very narrow, it should maybe be made taller by default:
![Screenshot_2021-04-19 Translate to Español_2](https://user-images.githubusercontent.com/871421/115272227-c6f74600-a103-11eb-9737-3ee422477bfe.png)

**Comment by indigoxela** [comment]
> ...A few visual/UI suggestions that come to mind...

@laryn many thanks for testing. The visual glitches should be fixed in 11ff8c9.

**Comment by laryn** [comment]
Looks great!
