### ISSUE TITLE
Submit buttons should be in 'actions' wrapper

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#68]
To take advantage of core button styling, can we wrap submit buttons in an actions container? I can make a PR.

**Comment by indigoxela** [comment]
A recent core change broke i18n tests. A fix is available now, but would require rebasing.

Also, it seems to me that the PR contains unneeded changes, where the #type already is "actions".

**Comment by indigoxela** [comment]
I'm trying to get a little closer to a stable release, merged. @laryn many thanks for your patience.
