### ISSUE TITLE
Column not found: 1054 Unknown column 'textgroup' in 'field list'

### ISSUE THREAD

**Issue by alanmels** [backdrop-contrib/i18n#7]
Trying to translate any term at, for example, `/en/admin/config/regional/translate/edit/1051` gives:

```
Error
Error messagePDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'textgroup' in 'field list': SELECT source, context, textgroup, location FROM {locales_source} WHERE lid = :lid; Array ( [:lid] => 1051 ) in i18n_string_locale_translate_edit_form() (line 294 of /var/www/docroot/modules/i18n/i18n_string/i18n_string.pages.inc).
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'textgroup' in 'field list': SELECT source, context, textgroup, location FROM {locales_source} WHERE lid = :lid; Array ( [:lid] => 1051 )
```

Will try to troubleshoot this tomorrow.

**Comment by indigoxela** [comment]
> Will try to troubleshoot this tomorrow.

lol, "tomorrow"...

@alanmels You might be interested in testing a new PR. See https://github.com/backdrop-contrib/i18n/issues/3 for details.

**Comment by indigoxela** [comment]
I suppose, this issue is outdated. If that's not the case, feel free to reopen it any time.
