### ISSUE TITLE
i18n_string doesn't recognize "locale_translate_english" setting

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#76]
When editing the English language, there is a setting to "Enable interface translation to English". This allows the site admin to rephrase things from the default on an English site. The `i18n_string` module doesn't recognize this. A PR is coming for review/discussion.

**Comment by laryn** [comment]
PR: https://github.com/backdrop-contrib/i18n/pull/77

**Comment by indigoxela** [comment]
@laryn many thanks for digging into this. Confirmed, currently the core setting is ignored, the PR fixes this.
