### ISSUE TITLE
Capitalize all 'translate' titles for consistency

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#91]
![Screen Shot 2022-03-04 at 9 25 31 AM](https://user-images.githubusercontent.com/871421/156791752-c1805f58-f162-47c4-bc73-08b9f6b278a5.jpg)

PR coming.

**Comment by laryn** [comment]
@indigoxela In the PR I've changed `'title' => t('translate'),` to `'title' => t('Translate'),` in a few places, but noticed there are a few that aren't wrapped in `t()`. Is there any reason for this or should I do that in this PR too? (e.g. `'title' => 'Translate',` like in `i18n.pages.inc`)

**Comment by indigoxela** [comment]
@laryn many thanks! Will likely merge this soon (tomorrow?).

> t() ... Is there any reason for this or should I do that in this PR too?

I think there's a reason. These code blocks look like preps for hook_menu, which is the only location, where t() is not needed for titles.
I'll have a closer look, if that's actually the case, but I'm pretty sure it is.

**Comment by indigoxela** [comment]
@laryn many thanks, I've merged this small and comprehensive fix.
