### ISSUE TITLE
Default language selection

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/i18n#93]
In another thread I mentioned this setting under **admin/config/regional/i18n/node**:
![Screen Shot 2022-03-10 at 4 19 00 PM](https://user-images.githubusercontent.com/871421/157764354-29663737-914e-4382-83f9-2e6ce69a819c.jpg)

This general setting can be overridden on a per-content-type basis:
![Screen Shot 2022-03-10 at 4 32 28 PM](https://user-images.githubusercontent.com/871421/157767410-980f3639-f0ac-48f1-83d0-4d92811f2b59.jpg)

It doesn't seem to work, however. I've got a PR that seems to work for me which I'll submit here for review.

**Comment by indigoxela** [comment]
@laryn many thanks for the report and PR. Need to dig a little deeper to fully understand the problem and patch. Stay tuned.

**Comment by indigoxela** [comment]
Ahem, wait...

```
Default language for content types with Multilingual support disabled.
```
Note the **Multilingual support DISABLED.**

It's not about the settings for multilingual sites - seems like a misunderstanding. :wink:

**Comment by laryn** [comment]
Ahem is right, but something is still wrong I think -- even without the node form having "Set current language..." checked it keeps showing the current language for me.

**Comment by indigoxela** [comment]
> even without the node form having "Set current language..." checked it keeps showing the current language for me.

Can you clarify that a bit? What is checked and what does "keeps showing the current language" mean?
What would you expect if there's no default setting? (If I get that part right...)

**Comment by laryn** [comment]
I'd like the default selection to be LANGUAGE_NONE but it keeps preselecting the current language, even though I haven't checked the box for "Set current language as default..." in the content type settings.

**Comment by indigoxela** [comment]
Ah, now I get it. Should be fixed in https://github.com/backdrop-contrib/i18n/commit/28a5f855f8f7a498cabb12b6e2069b75efd45766

**Comment by laryn** [comment]
Tested and it works!
